-- DROP DATABASE IF EXISTS exampledb;
-- CREATE DATABASE exampledb;

-- DROP DATABASE IF EXISTS testdb;
-- CREATE DATABASE testdb;


DROP DATABASE IF EXISTS dbPantryAssembler;
CREATE DATABASE dbPantryAssembler;


DROP DATABASE IF EXISTS itemlist;
CREATE DATABASE itemlist;